# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: ayltai/setup-graalvm@v1
      with:
        java-version: 11
        graalvm-version: 20.2.0
        native-image: true
    - name: Set GraalVM Home
      run: echo "GRAALVM_HOME=$JAVA_HOME" >> GITHUB_ENV
    - uses: actions/checkout@v2
    - name: Create and list all
      run: | # mvn client:build
        gu list
        echo JavaHome home below
        echo "$JAVA_HOME"
        echo JavaHome home Above
        printenv
 
