# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven CI Windows-Latest

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: ayltai/setup-graalvm@v1
      with:
        java-version: 11
        graalvm-version: 20.2.0
        native-image: true
    - name: Set GraalVM Home
      shell: bash
      run: | 
        echo "GRAALVM_HOME=$JAVA_HOME" >> $GITHUB_ENV
    - name: Enable Developer Command Prompt
      # You may pin to the exact commit or the version.
      # uses: ilammy/msvc-dev-cmd@ed94116c4d30d2091601b81f339a2eaa1c2ba0a6
      uses: ilammy/msvc-dev-cmd@v1.4.1
      with:
        # Target architecture
        arch: x64
        # Windows SDK number to build for
        sdk: 10.0.19041.0
        # VC++ compiler toolset version
        toolset: 14.25
    - uses: actions/checkout@v2
    - name: Create and list all
      shell: cmd
      run: | #
        mvn client:build
    - uses: actions/upload-artifact@v2
      with:
        name: x86_64-windows
        path: ./target/client/x86_64-windows/
