# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: ayltai/setup-graalvm@v1
      with:
        java-version: 11
        graalvm-version: 20.2.0
        native-image: true
    - name: Set GraalVM Home
      run: | 
        echo "GRAALVM_HOME=$JAVA_HOME" >> $GITHUB_ENV
    - name: Install Linker libs
      run: |
        sudo apt update
        sudo apt install libasound2-dev\
          libavcodec-dev\
          libavformat-dev\
          libavutil-dev\
          libfreetype6-dev\
          libgl-dev\
          libglib2.0-dev\
          libgtk-3-dev\
          libpango1.0-dev\
          libx11-dev\
          libxtst-dev\
          zlib1g-dev
    - uses: actions/checkout@v2
    - name: Create and list all
      run: | # 
        gu list
        mvn client:build
    - name: Zip Release
      uses: TheDoctor0/zip-release@0.4.1
      with: 
        filename: client.zip 
        path: ./target/client
    - name: Publish to release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: https://api.github.com/repos/kindlich/AppTestGluon/releases/32410469/assets 
        asset_path: ./client.zip
        asset_name: test
        asset_content_type: application/zip 
