# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven CI Android on Ubuntu-Latest

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: ayltai/setup-graalvm@v1
      with:
        java-version: 11
        graalvm-version: 20.2.0
        native-image: true
    - name: Set GraalVM Home
      run: | 
        echo "GRAALVM_HOME=$JAVA_HOME" >> $GITHUB_ENV
    - name: Install Linker libs
      run: |
        sudo apt update
        sudo apt install libasound2-dev\
          libavcodec-dev\
          libavformat-dev\
          libavutil-dev\
          libfreetype6-dev\
          libgl-dev\
          libglib2.0-dev\
          libgtk-3-dev\
          libpango1.0-dev\
          libx11-dev\
          libxtst-dev\
          zlib1g-dev
    - uses: actions/checkout@v2
    - name: Create and list all
      run: | # 
        gu list
        mvn client:build client:package -P android,!desktop
    - uses: actions/upload-artifact@v2
      with:
        name: android_client
        path: ./target/client/
        #TODO change later to proper subfolder
