# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: ayltai/setup-graalvm@v1
      with:
        java-version: 11
        graalvm-version: 20.2.0
        native-image: true
    - name: Install Graal NativeImage
      run: gu install native-image
    - uses: actions/checkout@v2
    - name: Create and list all
      env:
        GRAALVM_HOME: $JAVA_HOME
      run: |
        gu list
        mvn client:build
        find
 
