# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup GraalVM CE
      uses: rinx/setup-graalvm-ce@v0.0.1
      with:
        # GraalVM version: ex.) 19.3.0
        graalvm-version: 20.2.0
        # Java version: ex.) java8, java11
        java-version: java11

    - uses: actions/checkout@v2
    - name: Create and list all
      run: | 
        mvn client:build
        find
 
